sudo: required
services:
  - docker

before_install:
  - docker build -t shahmir811/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shahmir811/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-311569071766'
  bucket_path: 'docker-react'
  on:
    - branch: master
  access_key_id: $HOOLA_AWS_ACCESS_KEY_ID
  secret_access_key: $HOOLA_AWS_SECRET_KEY
